<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%-- StudyModal.open({ type:'input', theme:'danger', title:'비밀번호 확인', message:'계속하려면 현재 비밀번호를 입력해 주세요.', onConfirm:function(password){ ... } }); --%>
<div id="studyInputModal" class="study-modal" aria-hidden="true">
    <div class="study-modal__backdrop" data-cancel></div>
    <section class="study-modal__card" role="dialog" aria-modal="true" aria-labelledby="studyInputTitle">
        <div class="study-modal__icon" aria-hidden="true">🔒</div><h2 id="studyInputTitle" class="study-modal__title"></h2><p class="study-modal__message"></p>
        <label class="study-modal__sr-only" for="studyModalPassword">비밀번호</label><input id="studyModalPassword" class="study-modal__input" type="password" autocomplete="current-password">
        <p class="study-modal__error" aria-live="polite"></p>
        <div class="study-modal__actions"><button type="button" class="study-modal__button study-modal__button--secondary" data-cancel>취소</button><button type="button" class="study-modal__button study-modal__button--primary" data-confirm>확인</button></div>
    </section>
</div>
<style>
.study-modal{display:none;position:fixed;z-index:1050;inset:0;align-items:center;justify-content:center;font-family:inherit}.study-modal.is-open{display:flex}.study-modal__backdrop{position:absolute;inset:0;background:rgba(17,24,39,.5)}.study-modal__card{position:relative;box-sizing:border-box;width:min(420px,calc(100% - 32px));padding:28px;border-radius:16px;background:#fff;box-shadow:0 20px 45px rgba(0,0,0,.2);text-align:center}.study-modal__icon{display:flex;align-items:center;justify-content:center;width:48px;height:48px;margin:0 auto 14px;border-radius:50%;background:#e8f5e9;color:#2e7d32;font-size:23px}.study-modal__title{margin:0;color:#1f2937;font-size:20px}.study-modal__message{margin:10px 0 18px;color:#6b7280;line-height:1.55;white-space:pre-line}.study-modal__input{box-sizing:border-box;width:100%;border:1px solid #d1d5db;border-radius:8px;padding:12px;font:inherit;outline:none}.study-modal__input:focus{border-color:#4caf50;box-shadow:0 0 0 3px rgba(76,175,80,.15)}.study-modal__error{min-height:20px;margin:6px 0 10px;color:#d32f2f;font-size:13px;text-align:left}.study-modal__actions{display:flex;gap:8px;justify-content:center}.study-modal__button{min-width:110px;border:0;border-radius:8px;padding:11px 16px;font:inherit;font-weight:600;cursor:pointer}.study-modal__button--primary{background:#4caf50;color:#fff}.study-modal__button--secondary{background:#f3f4f6;color:#374151}.study-modal__sr-only{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0,0,0,0)}.study-modal[data-theme="danger"] .study-modal__icon{background:#ffebee}.study-modal[data-theme="danger"] .study-modal__button--primary{background:#e53935}.study-modal[data-theme="warning"] .study-modal__button--primary{background:#f59e0b}.study-modal[data-theme="info"] .study-modal__button--primary{background:#1976d2}
</style>
<script>
(function(){var root=document.getElementById('studyInputModal'),title=root.querySelector('.study-modal__title'),message=root.querySelector('.study-modal__message'),input=root.querySelector('.study-modal__input'),error=root.querySelector('.study-modal__error'),current={};function close(cancelled){root.classList.remove('is-open');root.setAttribute('aria-hidden','true');if(cancelled&&typeof current.onCancel==='function')current.onCancel();}function open(options){current=options||{};root.dataset.theme=current.theme||'info';title.textContent=current.title||'비밀번호 확인';message.textContent=current.message||'';input.value='';input.placeholder=current.placeholder||'비밀번호를 입력해 주세요.';error.textContent='';root.classList.add('is-open');root.setAttribute('aria-hidden','false');setTimeout(function(){input.focus();},0);}function submit(){if(!input.value){error.textContent=current.requiredMessage||'비밀번호를 입력해 주세요.';input.focus();return;}var callback=current.onConfirm,password=input.value;close(false);if(typeof callback==='function')callback(password);}root.querySelector('[data-confirm]').addEventListener('click',submit);input.addEventListener('keydown',function(event){if(event.key==='Enter')submit();});root.querySelectorAll('[data-cancel]').forEach(function(button){button.addEventListener('click',function(){close(true);});});document.addEventListener('keydown',function(event){if(event.key==='Escape'&&root.classList.contains('is-open'))close(true);});window.StudyModal=window.StudyModal||{registry:{}};window.StudyModal.registry.input={open:open,close:close};window.StudyModal.open=function(options){var modal=this.registry[options&&options.type];if(!modal)throw new Error('등록되지 않은 modal type입니다.');modal.open(options);};})();
</script>
